<!DOCTYPE html>
<!-- 
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise

Promise.any() 接收一个Promise可迭代对象，只要其中的一个 promise 成功，就返回那个已经成功的 promise 。
如果可迭代对象中没有一个 promise 成功（即所有的 promises 都失败/拒绝），就返回一个失败的 promise 和AggregateError类型的实例，
它是 Error 的一个子类，用于把单一的错误集合在一起。本质上，这个方法和Promise.all()是相反的。
-->
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    const pErr = new Promise((resolve, reject) => {
      reject("总是失败");
    });

    const pSlow = new Promise((resolve, reject) => {
      // setTimeout(resolve, 500, "最终完成");
      setTimeout(reject, 500, "最终失败");
    });

    const pFast = new Promise((resolve, reject) => {
      // setTimeout(resolve, 100, "很快完成");
      setTimeout(reject, 100, "很快失败");
    });

    Promise.any([pErr, pSlow, pFast]).then((value) => {
      console.log(value);
      // pFast fulfils first
    }).catch(e => {
      console.log(e instanceof AggregateError); // true
      console.log(e.message);                   // "All Promises rejected"
      console.log(e.name);                      // "AggregateError"
      console.log(e.errors);                    //  ["总是失败", "最终失败", "很快失败"]
    });

    // 期望输出: "很快完成"

  </script>
</body>

</html>